/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecoyRouteImport } from './routes/decoy'
import { Route as FinalRouteImport } from './routes/final'
import { Route as FragmentRouteImport } from './routes/fragment'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoyRoute = DecoyRouteImport.update({
  id: '/decoy',
  path: '/decoy',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const FragmentRoute = FragmentRouteImport.update({
  id: '/fragment',
  path: '/fragment',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decoy': typeof DecoyRoute
  '/final': typeof FinalRoute
  '/fragment': typeof FragmentRoute
  '/leaderboard': typeof LeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decoy': typeof DecoyRoute
  '/final': typeof FinalRoute
  '/fragment': typeof FragmentRoute
  '/leaderboard': typeof LeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decoy': typeof DecoyRoute
  '/final': typeof FinalRoute
  '/fragment': typeof FragmentRoute
  '/leaderboard': typeof LeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decoy' | '/final' | '/fragment' | '/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decoy' | '/final' | '/fragment' | '/leaderboard'
  id: '__root__' | '/' | '/decoy' | '/final' | '/fragment' | '/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecoyRoute: typeof DecoyRoute
  FinalRoute: typeof FinalRoute
  FragmentRoute: typeof FragmentRoute
  LeaderboardRoute: typeof LeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoy': {
      id: '/decoy'
      path: '/decoy'
      fullPath: '/decoy'
      preLoaderRoute: typeof DecoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragment': {
      id: '/fragment'
      path: '/fragment'
      fullPath: '/fragment'
      preLoaderRoute: typeof FragmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecoyRoute: DecoyRoute,
  FinalRoute: FinalRoute,
  FragmentRoute: FragmentRoute,
  LeaderboardRoute: LeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
